adjust logic to work with prefect 2.0
RealImpactAnalytics/snd-reporting pull request #23
Opened 2023-07-17 11:43 UTC by axelearning

2023-07-17 12:09 UTC, massintha-riaktr requested changes

2023-07-17 12:09 UTC, massintha-riaktr commented on provisioning/Dockerfile
> +FROM riaktr/python-packager:snd-4.2.0 as etl-deps
snd-4.2.0-5

2023-07-17 12:09 UTC, massintha-riaktr commented on provisioning/Dockerfile
> +FROM riaktr/flows-provisioning:snd-4.2.0
snd-4.2.0-5

2023-07-17 12:09 UTC, massintha-riaktr commented on etl_code/flows/prefect_flows/custom_export.py
> +@flow(name=FLOW_NAME, flow_run_name=f"{FLOW_NAME}-{{observation_date}}", **get_prefect_flow_config(FLOW_NAME))
are we using the parameter for the days delay configuration?

because for the flow run name to use the actual observation date you can use
```
from mjolnir_python.prefect_utils.flow_utils import get_generate_flow_name
....
flow_run_name=get_generate_flow_name(FLOW_NAME)

2023-07-17 12:42 UTC, axelearning commented on etl_code/flows/prefect_flows/custom_export.py
> +@flow(name=FLOW_NAME, flow_run_name=f"{FLOW_NAME}-{{observation_date}}", **get_prefect_flow_config(FLOW_NAME))
do you mean having this 
```python
@flow(name=FLOW_NAME, flow_run_name=get_generate_flow_name(FLOW_NAME), **get_prefect_flow_config(FLOW_NAME))
```

2023-07-20 08:15 UTC, merged

2023-07-20 12:20 UTC, massintha-riaktr commented
@axelearning don't forget to cherry pick this to develop