Migrate Ct/GT report
RealImpactAnalytics/snd-reporting pull request #5
Opened 2023-03-23 15:44 UTC by axelearning

## Goal 
migrate the [ct-gt report](https://github.com/RealImpactAnalytics/snd-reporting-tool/blob/5320224dc787a7634b8455626c935ca688135419/report_code/client_reports/field/field_report.py) inside SND report section. 

## Test 
to merge this PR, the following test need to be validated
> pass test old_excel_file == new_excel_file

2023-05-31 08:17 UTC, MaximeBastion requested changes
Great work!

2023-05-31 08:17 UTC, MaximeBastion commented on etl_code/flows/data_store/reports.py
> +)
Is this used?

2023-05-31 11:10 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/design.py
> +    #     sheet1.worksheet.write(row, 1, legend.iat[row - 4, 0], bold_format)
indeed Thanks Maxime

2023-05-31 14:53 UTC, massintha-riaktr commented on etl_code/jobs/csm_reports/utils/sql.py
> +        .option("url", "jdbc:postgresql://data-broker-service-db:5432/data_modules")
and in 4.2 we have the new `SparkJdbcConnector` 😄

2023-05-31 15:07 UTC, massintha-riaktr requested changes

2023-05-31 15:07 UTC, massintha-riaktr commented on exploration/gt_report.csv
> +username,teams,geo_places,working_days,number_of_self_assigned_tasks,number_of_tasks_assigned_by_snd_user,number_of_tasks_assigned_by_ct_user,number_of_tasks_completed,number_of_check_in,number_of_po
this shouldn't be pushed right?

2023-05-31 15:07 UTC, massintha-riaktr commented on exploration/gt_report.csv
> +username,teams,geo_places,working_days,number_of_self_assigned_tasks,number_of_tasks_assigned_by_snd_user,number_of_tasks_assigned_by_ct_user,number_of_tasks_completed,number_of_check_in,number_of_po
same with the excel file

2023-05-31 15:07 UTC, massintha-riaktr commented on etl_code/jobs/csm_reports/gt_report/translation/en.py
> +
why all these empty lines?

2023-05-31 15:07 UTC, massintha-riaktr commented on etl_code/jobs/csm_reports/gt_report/logic/link_region.py
> +    return tasks.filter(F.col("rank") == 1).drop("count", "rank")
it weird to have a function that drops and filter on columns that it didn't even create. This should be merged with `_rank_by_occurrence` IMO

2023-06-02 08:10 UTC, axelearning commented on etl_code/flows/connectors/minio_excel_connector.py
> +    def minio_client(self)->Minio:
good idea I will run black on top of it

2023-06-02 08:13 UTC, axelearning commented on etl_code/flows/data_store/reports.py
> +)
no indeed

2023-06-02 08:17 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/config.py
> +    target: int
indeed let's call it task_targeted

2023-06-02 08:22 UTC, axelearning commented on etl_code/jobs/csm_reports/utils/time_frame.py
> +def get_time_frames(run_date: str, frequency: Frequency, format:str='%Y-%m-%d') -> TimeFrame:
yes for the moment we are not using the comparaison tf

2023-06-02 08:34 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/translation/en.py
> +    "Visit": "",
yes waiting ofr nico output

2023-06-02 08:34 UTC, axelearning commented on etl_code/jobs/csm_reports/utils/format.py
> +def format(df:DataFrame)->DataFrame:
not used indeed good catch

2023-06-02 08:34 UTC, axelearning commented on etl_code/flows/data_store/reports.py
> +)
no thanks

2023-06-02 08:35 UTC, axelearning commented on etl_code/jobs/csm_reports/utils/format.py
> +   ['Distributeur Teddycom', 'Distributeur Teddycom2'] into DISTRIBUTEUR TEDDYCOM - DISTRIBUTEUR TEDDYCOM2
example of distributeur in MOOV

2023-06-02 08:36 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/translation/en.py
> +
wainting on nico input

2023-06-14 09:18 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/logic/integrity_rate.py
> +    time_computation_logic = F.when( F.col("previous_completed_at").isNull(), F.lit(None) ).otherwise( F.col("completed_at_ts") - F.col("previous_completed_at_ts") )
yes good point max. We can simply to id like follow
```python
F.col("completed_at_ts") - F.col("previous_completed_at_ts")
```

2023-06-14 09:22 UTC, axelearning commented on etl_code/jobs/csm_reports/utils/sql.py
> +        .option("url", "jdbc:postgresql://data-broker-service-db:5432/data_modules")
> indeed to be extracted from the configuration

can we use the one from [airflow-connection](https://github.com/RealImpactAnalytics/ce-mtn-bj-delivery/blob/89125fd9797aa304484748e78141a24ec4aaf631/config/pipeline/airflow-connections.yaml#L27-L35) ?

2023-06-14 09:26 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/translation/parse.py
> +        raise ValueError("'config variable language' needs to be 'FR' or 'EN'")
thanks this is much nicer

2023-06-14 09:28 UTC, axelearning commented on exploration/gt_report.csv
> +username,teams,geo_places,working_days,number_of_self_assigned_tasks,number_of_tasks_assigned_by_snd_user,number_of_tasks_assigned_by_ct_user,number_of_tasks_completed,number_of_check_in,number_of_po
yes indeed

2023-06-14 09:33 UTC, axelearning commented on etl_code/jobs/csm_reports/utils/time_frame.py
> +        analyzed_start_date = analyzed_end_date - timedelta(days=_get_last_day_of_previous_month(analyzed_end_date))
indeed make it better

2023-06-14 12:47 UTC, massintha-riaktr commented on etl_code/flows/connectors/minio_excel_connector.py
> +    def minio_client(self) -> Minio:
if you want to have a client to reuse you better add it in the `__post_init__` function or else each time you call `minio_client` it will initialize a new client

2023-06-14 12:47 UTC, massintha-riaktr commented on etl_code/jobs/csm_reports/gt_report/logic/integrity_rate.py
> +    THRESHOLD_TIME_SECONDS = 120
wouldn't be this be nice to have it as a configuration instead?

2023-06-14 12:47 UTC, massintha-riaktr commented on etl_code/jobs/csm_reports/utils/sql.py
> +        .option("url", "jdbc:postgresql://data-broker-service-db:5432/data_modules")
yes you can. There is already some examples https://github.com/RealImpactAnalytics/ce-orange-ml-delivery/blob/f39db9442e5420b33c01d140a6afe2fe476cf742/etl_code/jobs/utils.py#L17

2023-06-14 12:47 UTC, axelearning commented on etl_code/jobs/csm_reports/gt_report/logic/integrity_rate.py
> +    THRESHOLD_TIME_SECONDS = 120
indeed will do this

2023-06-14 13:18 UTC, massintha-riaktr approved these changes

2023-06-14 15:16 UTC, merged